const Colors={Black:"#4F6367",
                Orange:"#f0ad4e",
                White:"#f7f7f7",
                Red:"#d9534f",
                Green:"#5cb85c",
                Blue:"#FE5F55",
                lightOrange:"#f0ad4e",
                SILVER: '#efefef',
                secondry:"#f7f7f7",
                button:"#FD8700",
                error:"#D9534F",
                BLUE: '#3543bf',
                ORANGE: '#f0ad4e',
                GREEN: '#30a960',
                RED: '#f06159',
                BLACK: '#0b0b0b',
                SILVER: '#efefef',
                WHITE: '#fff',
                GREY: '#7e7e7e',
                WHITE_GREY: '#d4d4d4',
                DARK_GREY: '#555555',
                LIGHT_BLACK: '#212121',
                DARK_RED: '#c04d47',
                SEMI_TRANSPARENT: 'rgba(0,0,0,0.5)',
                LIGHT_RED: '#fef3ec',
                YELLOW: '#fec72e',
                LIGHT_GREY: '#a9a9a9',
                PALE_YELLOW: '#fff6ef',
                DARK_BLUE: '#2e68b2',
                LIGHT_BLUE: '#EEEFF9',
                boot_darkblue:"#0275d8",
                boot_green:"#5cb85c",
                boot_yellow:"#f0ad4e",
                boot_red:"#d9534f",
                boot_black:"#292b2c",
                red_pro:"#EF6A62",
            Link:"#5BC0DE",
            App_back:"#12385C",
            button_yellow:"#FCCF3E",
            primary:"#fec72e",
            secondry:"#f7f7f7",
            button:"#FD8700",
            red:"#ED5565",
            Darkred:"#DA4453",
            Orange:"#fec72e",
            MAFRREON:"#E9573F",
            YELLOW:"#f0ad4e",
            dARK_YELLOW:"#f0ad4e",
            GREEN:"#AOD468",  
            dARK_gREEN:"#37BC98", 
            LIGHT_GREEN:"#48CFAD", 
            gREEN_COLL:"#fec72e", 
            bLUE:"#12385C",
            DARK_BLUE:"#3BAFDA",
            nAVY_BLUE:"#5D9CEC",
            oCEN_BLUE:"#4A89DC",
            pURPLE:"#AC92EC",
            pURPLE_DARK:"#967ADC",
            pINK:"#EC87C0",
            pINK_ROSE:"#D770AD",
            wHITE:"#F5F7FA",
            lIGHT_GREY:"#E6E9ED",
            gREY_mEDIUM:"#CCD1D9",
            GREY_DARK:"#AAB2BD",
            gREY:"#656D78",
            BLACK:"#434A54",
            button:"#FD8700",
                error:"#D9534F",
                BLUE: '#3543bf',
               
                ORANGE: '#f0ad4e',
                GREEN: '#30a960',
                RED: '#f06159',
                BLACK: '#0b0b0b',
                SILVER: '#efefef',
                WHITE: '#fff',
                GREY: '#7e7e7e',
                WHITE_GREY: '#d4d4d4',
                DARK_GREY: '#555555',
                LIGHT_BLACK: '#212121',
                DARK_RED: '#c04d47',
                SEMI_TRANSPARENT: 'rgba(0,0,0,0.5)',
                LIGHT_RED: '#fef3ec',
                YELLOW: '#fec72e',
                LIGHT_GREY: '#a9a9a9',
                PALE_YELLOW: '#fff6ef',
                DARK_BLUE: '#2e68b2',
                LIGHT_BLUE: '#EEEFF9',};
    
export default Colors;